import type { Metadata } from "next";
import "./globals.css";
import { ProvedorBlog } from "@/data/context/ContextoBlog";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`antialiased`}
      >
        <ProvedorBlog>
          {children}
        </ProvedorBlog>
      </body>
    </html>
  );
}
