GET http://localhost:8080/books

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "author": "J. R. R. Tolkien",
  "genre": "Fantasy"
}

###

GET http://localhost:8080/books/1

###

PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "author": "J. R. R. Tolkien",
  "genre": "Fantasy"
}

###

DELETE http://localhost:8080/books/1